### ISSUE TITLE
Problem in reproduce process

### ISSUE THREAD

**Issue by shaun919** [szc19990412/TransMIL#12]
It seems that you load the '.pt' file in 'camel_data.py'. I'm wondering whether you made feature extraction on dataset, and it is quite appealing for me to figure out what happened behind the code.

It would be appreciated if you could help me.

**Comment by szc19990412** [comment]
Hi, we use CLAM's WSI processing solution (https://github.com/mahmoodlab/CLAM), hope this can help you
