### ISSUE TITLE
Split rule about TCGA datasets

### ISSUE THREAD

**Issue by DearCaat** [szc19990412/TransMIL#16]
Hello,
Could you please provide more details on generating TCGA datasets? I found on the official website that TCGA-LUAD contains 585 cases and more than 1000 slides, and TCGA-RCC is similar.

**Comment by szc19990412** [comment]
Hello, the division of the data set must first ensure that the different WSIs of a patient cannot exist in the training and testing sets at the same time.  Therefore, for the TCGA dataset, patients need to be divided.
