### ISSUE TITLE
Float  vs.   Half

### ISSUE THREAD

**Issue by 1633146782** [szc19990412/TransMIL#18]
RuntimeError:expected scalar type Float but found Half

Run train.py files meet this issus,could anybody help me solve it ?   thanks

**Comment by peakhong** [comment]
I have the same mistake. Have you solved it?

**Comment by szc19990412** [comment]
I think this is due to different versions of pytorch lightning framework.  Maybe you can try the setting of pytorch_lightning==1.2.3, pytorch_toolbelt==0.4.0.

**Comment by 1633146782** [comment]
thank you, I will try it again according your advice 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月7日(星期五) 上午10:30
收件人: "szc19990412/TransMIL";
抄送: "Author";
主题: Re: [szc19990412/TransMIL] Float  vs.   Half (Issue #18)





 
I think this is due to different versions of pytorch lightning framework.  Maybe you can try the setting of pytorch_lightning==1.2.3, pytorch_toolbelt==0.4.0.
 
&mdash;
