### ISSUE TITLE
What is the number of patches of each WSIs?

### ISSUE THREAD

**Issue by Furyboyy** [szc19990412/TransMIL#20]
Some WSIs have only 2048 patches, some have over 40000 patches. In your paper, you used a `Squaring` method to pad the embeddings to a fixed length. What is the fixed length? If the largest WSI has 50000 patches, did you pad all the embeddings to (1, 50000,  1024) ?

**Comment by szc19990412** [comment]
We process it at 20x resolution, and we tend to get only about 20,000 patches at most in WSI. For example, if a WSI has only 2048 patches, we will pad the embeddings to (1, 2116, 1024), and if a WSI has 50,000 patches, we will pad the embeddings to (1, 50176, 1024). The amount of padding is determined by the number of patches in the WSI itself.

**Comment by Furyboyy** [comment]
Thank you for your reply!
But I can't understand your reply.

`The amount of padding is determined by the number of patches in the WSI itself.`
How did you determine the padding with the number of patches in the WSI?

I can't see any logic in padding 2048 -> 2116 and pad 50000 -> 50176. @szc19990412

**Comment by HHHedo** [comment]
> We process it at 20x resolution, and we tend to get only about 20,000 patches at most in WSI. For example, if a WSI has only 2048 patches, we will pad the embeddings to (1, 2116, 1024), and if a WSI has 50,000 patches, we will pad the embeddings to (1, 50176, 1024). The amount of padding is determined by the number of patches in the WSI itself.

Thank you for your reply！
In the process of spatial restoration, did you use the spatial coordinate of patches?
