### ISSUE TITLE
How to make interpretability and attention visualization？Just like Figure 6 in the paper TransMIL.

### ISSUE THREAD

**Issue by PerrySkywalker** [szc19990412/TransMIL#21]

**Comment by szc19990412** [comment]
First, get the self attention matrix of [nystrom attention](https://github.com/lucidrains/nystrom-attention/blob/eec98bc62a1ee6f7d8d89f6c71186a9cc568fc8b/nystrom_attention/nystrom_attention.py#L67) (set the return_attn =True).  Then take out the column corresponding to the class token, that is, the attention of the class token to the rest of the feature tokens. Finally, we follow the [CLAM](https://github.com/mahmoodlab/CLAM/tree/master/heatmaps) framework.

**Comment by PerrySkywalker** [comment]
Ok, thank you very much.

**Comment by DeVriesMatt** [comment]
Sorry, I still don't understand. The output shape of the nystrom attention (when return_attn=True), is [B, num_head, x, x] (where I don't know what x is). Do you have the code for this?

**Comment by PerrySkywalker** [comment]
> 

https://github.com/jacobgil/vit-explain

> Sorry, I still don't understand. The output shape of the nystrom attention (when return_attn=True), is [B, num_head, x, x] (where I don't know what x is). Do you have the code for this?

https://github.com/jacobgil/vit-explain， watch this.

**Comment by Rokinluohhh** [comment]
> > 
> 
> https://github.com/jacobgil/vit-explain
> 
> > Sorry, I still don't understand. The output shape of the nystrom attention (when return_attn=True), is [B, num_head, x, x] (where I don't know what x is). Do you have the code for this?
> 
> [https://github.com/jacobgil/vit-explain，](https://github.com/jacobgil/vit-explain%EF%BC%8C) watch this.

Do you know how to take out the column corresponding to the class token?

**Comment by Rokinluohhh** [comment]
> > 
> 
> https://github.com/jacobgil/vit-explain
> 
> > Sorry, I still don't understand. The output shape of the nystrom attention (when return_attn=True), is [B, num_head, x, x] (where I don't know what x is). Do you have the code for this?
> 
> [https://github.com/jacobgil/vit-explain，](https://github.com/jacobgil/vit-explain%EF%BC%8C) watch this.

Can you provide your code about visualization part?thanks very much!

**Comment by PerrySkywalker** [comment]
> > > 
> > 
> > 
> > https://github.com/jacobgil/vit-explain
> > > Sorry, I still don't understand. The output shape of the nystrom attention (when return_attn=True), is [B, num_head, x, x] (where I don't know what x is). Do you have the code for this?
> > 
> > 
> > [https://github.com/jacobgil/vit-explain，](https://github.com/jacobgil/vit-explain%EF%BC%8C) watch this.
> 
> Can you provide your code about visualization part?thanks very much!

Ok, I will upload the code to my GitHub in a week.

**Comment by Rokinluohhh** [comment]
> > > > 
> > > 
> > > 
> > > https://github.com/jacobgil/vit-explain
> > > > Sorry, I still don't understand. The output shape of the nystrom attention (when return_attn=True), is [B, num_head, x, x] (where I don't know what x is). Do you have the code for this?
> > > 
> > > 
> > > [https://github.com/jacobgil/vit-explain，](https://github.com/jacobgil/vit-explain%EF%BC%8C) watch this.
> > 
> > 
> > Can you provide your code about visualization part?thanks very much!
> 
> Ok, I will upload the code to my GitHub in a week.

Wow!Thanks a lot!
