### ISSUE TITLE
No such file or directory: 'Camelyon16/pt_files/normal_024.pt'

### ISSUE THREAD

**Issue by jieruyao49** [szc19990412/TransMIL#22]
The directory of the camelyon16 dataset I downloaded is as follows. Where should I download the .pt files?

```
CAMELYON16
  -training
     -normal
        -normal_xxx.tif
     -turmor
        -turmor_xxx.tif
     -lesion_annotation
        -turmor_xxx.xml
  -testing
     -images
        -test_xxx.tif
     -evaluation
        -evaluation_masks.zip
        -evaluation_matlab.zip
        -evaluation_python.zip
```

**Comment by szc19990412** [comment]
We use the [CLAM](https://github.com/mahmoodlab/CLAM) method to process WSI, and we can acquire the matching pt file, which corresponds to all patches in each WSI's features.
