### ISSUE TITLE
ABMIL in comparison

### ISSUE THREAD

**Issue by InfinityBox** [szc19990412/TransMIL#7]
I'm just wondering how to apply ABMIL in WSI for the comparison in Table 1? 
I have read ABMIL's code, the input size of its model is: (1, bag_length, 1, width, height), due to the images of the dataset being very small, memory problems may not occur. But when using WSI, bag_length, width and height are very big, so how to apply this method to WSIs like the result in Table 1?

**Comment by szc19990412** [comment]
There may be some misunderstanding of the references here. 
You can refer to the code here to implement ABMIL, which is an attention MIL based on features：
https://github.com/mahmoodlab/PORPOISE/blob/master/models/model_attention_mil.py
